services:
  backend:
    container_name: gedasc-backend
    build:
      context: ./database
    environment:
      - TZ=America/Bogota
    env_file:
      - ./database/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gedasc-internal
      - proxy-network
    restart: always

  postgres:
    container_name: gedasc-postgres
    image: postgres:16
    environment:
      - TZ=America/Bogota
      - PGTZ=America/Bogota
    env_file:
      - ./database/.env_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d GEDASC"]
      interval: 4s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - gedasc-internal
    restart: always

  frontend:
    container_name: gedasc-frontend
    build:
      context: ./
      args:
        VITE_API_URL: https://api-gedasc.adsoproject.dev
    networks:
      - gedasc-internal
      - proxy-network
    restart: always

volumes:
  postgres_data:

networks:
  gedasc-internal:
    driver: bridge
  proxy-network:
    external: true
